
# Contains all the prompts used in the program - gpt & distress


#gpt Set of prompts which would need GPT-3.5 turbo model for better results

gpt = [
    "Tell me a story about",
    "Explain how",
    "What is the meaning of",
    "Can you help me understand",
    "Suggest some tips for",
    "Compare and contrast",
    "List the benefits of",
    "Discuss the pros and cons of",
    "How does it work when",
    "Provide an example of",
    "Explain the concept of",
    "Give me advice on",
    "What are the implications of",
    "How can I improve my",
    "Tell me about the history of",
    "Provide insights into",
    "Clarify the relationship between",
    "Elaborate on the process of",
    "Discuss the importance of",
    "Examine the challenges in",
    "Recommend resources for",
    "How do I get started with",
    "Can you predict the future of",
    "Share your thoughts on",
    "Analyze the impact of",
    "Help me troubleshoot",
    "What are the ethical considerations of",
    "Provide a step-by-step guide for",
    "Elaborate on the benefits of",
    "What are some common misconceptions about",
    "Describe the characteristics of",
    "Discuss the role of",
    "What are the key features of",
    "Explain the significance of",
    "Provide examples of",
    "Can you clarify the concept of",
    "What are the potential risks of",
    "Offer insights into",
    "Discuss the challenges faced by",
    "How does technology impact",
    "Explain the basics of",
    "What are the benefits of learning",
    "Provide an overview of",
    "Compare the similarities and differences between",
    "What are the current trends in",
    "Discuss the future prospects of",
    "Elaborate on the process of",
    "Provide guidance on",
    "What is the relationship between",
    "Explain the steps to",
    "What is the significance of",
    "How can I address the issue of",
    "What are some strategies for",
    "Discuss the cultural impact of",
    "Explain the factors influencing",
    "What are the different types of",
    "Provide examples of successful",
    "Elaborate on the concept of",
    "What are the implications of",
    "Discuss the benefits of",
    "What are the challenges associated with",
    "Explain the concept of",
    "What is the role of",
    "Can you provide tips for",
    "Discuss the impact of",
    "Explain the relationship between",
    "What are the steps to",
    "Provide insights into the history of",
    "Discuss the benefits and drawbacks of",
    "What is the future of",
    "Explain the process of",
    "What are the key factors in",
    "Provide recommendations for",
    "Discuss the impact of globalization on",
    "Explain the concept of sustainability in",
    "What are the advantages of",
    "Elaborate on the importance of",
    "Discuss the challenges related to",
    "What is the connection between",
    "Provide an analysis of",
    "Explain the significance of",
    "What are the key principles of",
    "Discuss the role of innovation in",
    "Explain the impact of technology on",
    "What are the benefits of using",
    "Provide examples of ethical dilemmas in",
    "Discuss the implications of artificial intelligence in",
    "What is the history of",
    "Elaborate on the concept of social responsibility in",
    "What are the best practices for",
    "Explain the cultural significance of",
    "Discuss the importance of education in",
    "What is the relationship between culture and",
    "Provide insights into the future of",
    "Discuss the ethical implications of",
    "Explain the benefits of diversity in",
    "What are the key challenges in",
    "Discuss the impact of climate change on",
    "What is the role of ethics in",
    "Provide an overview of the challenges in",
    "Explain the concept of digital transformation in",
    "What are the effects of",
    "Elaborate on the concept of leadership in",
    "Discuss the impact of social media on",
    "What is the connection between health and",
    "Provide examples of successful initiatives in",
    "Discuss the influence of media on",
    "What is the future outlook for",
    "Explain the concept of democracy in",
    "What are the implications of artificial intelligence on",
    "Discuss the role of government in",
    "What is the significance of cultural diversity in",
    "Provide insights into the role of technology in",
    "Explain the impact of globalization on",
    "Discuss the challenges of urbanization in",
    "What are the benefits of sustainable practices in",
    "Elaborate on the concept of economic development in",
    "Tell me more about that.",
    "Can you elaborate?",
    "What are some examples?",
    "I'd like to know more.",
    "Could you explain further?",
    "What's your opinion on this?",
    "How does that work?",
    "Do you have any recommendations?",
    "Could you clarify?",
    "What are the pros and cons?",
    "What else can you tell me?",
    "Can you provide more insights?",
    "I'm interested in learning more.",
    "What's the impact of this?",
    "Could you discuss the challenges?",
    "What's the significance of this?",
    "Tell me about related topics.",
    "How can I apply this in real life?",
    "What are some practical tips?",
    "What's the current state of research?",
    "Can you give me more details?",
    "What are some possible solutions?",
    "Are there any potential drawbacks?",
    "Tell me about historical examples.",
    "How do experts view this?",
    "Could you break it down?",
    "Tell me about recent developments.",
    "What's the long-term outlook?",
    "Can you share statistics?",
    "What's the role of ethics here?",
    "What do studies say about this?",
    "How can I get started with this?",
    "Are there any success stories?",
    "What's the future direction?",
    "Can you give a step-by-step guide?",
    "What are the common misconceptions?",
    "Tell me about relevant trends.",
    "Could you provide a summary?",
    "How does this impact society?",
    "What are the key takeaways?"
]

# distress prompts to send distress audio to responsible organization
distress = [
        "Urgent help needed!",
    "Emergency situation!",
    "Immediate assistance required!",
    "Life-threatening crisis!",
    "Critical danger, respond ASAP!",
    "Please dispatch help now!",
    "Serious threat, intervene!",
    "Dangerous situation unfolding!",
    "Immediate intervention necessary!",
    "Report urgent incident!",
    "Please assist immediately!",
    "Respond to critical emergency!",
    "Life in imminent danger!",
    "Situation is dire!",
    "Need authorities on-site now!",
    "Call for emergency response!",
    "Respond urgently!",
    "Help required urgently!",
    "Immediate action required!",
    "Respond ASAP, urgent crisis!",
    "Critical incident, respond now!",
    "Dispatch help immediately!",
    "Dangerous circumstances, act fast!",
    "Request immediate assistance!",
    "Urgent situation, deploy responders!",
    "Emergency, need help now!",
    "Serious trouble, call authorities!",
    "Dangerous situation, please help!",
    "Immediate support necessary!",
    "Report critical incident!",
    "Life at risk, respond urgently!",
    "Seeking help for dire situation!",
    "Respond quickly, urgent situation!",
    "Immediate intervention needed!",
    "Crisis unfolding, respond now!",
    "Urgent call for assistance!",
    "Notify authorities, immediate!",
    "Threat escalating, act now!",
    "Emergency alert, respond urgently!",
    "Urgent distress, send help!",
    "Dangerous conditions, please respond!",
    "Critical help required!",
    "Emergency assistance needed!",
    "Time-sensitive crisis, act now!",
    "Report life-threatening situation!",
    "Urgent distress signal, respond!",
    "Situation is critical, respond fast!",
    "Requesting immediate intervention!",
    "Crisis situation, respond urgently!",
    "Life in peril, respond immediately!",
    "Notify authorities, urgent!",
    "Emergency response needed!",
    "Critical incident, act now!",
    "Immediate attention required!",
    "Urgent call for intervention!",
    "Emergency situation, respond fast!",
    "Need help urgently, critical!",
    "Request urgent support!",
    "Life-threatening issue, respond now!",
    "Act fast, dangerous situation!",
    "Critical distress, immediate response!",
    "Emergency alert, respond promptly!",
    "Urgent assistance required!",
    "Notify authorities, critical!",
    "Crisis unfolding, respond ASAP!"
]